// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBiQa_XJ9PGd_IF8962pjisx1MmAPypvs',
    appId: '1:824061143111:web:c7cec946c57df50676e962',
    messagingSenderId: '824061143111',
    projectId: 'task-manager-94870',
    authDomain: 'task-manager-94870.firebaseapp.com',
    storageBucket: 'task-manager-94870.appspot.com',
    measurementId: 'G-5CE2TSWKW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Liws8CzfM5ssS9du1qiZNWKlNXbvNzk',
    appId: '1:824061143111:android:09fd26df23733f5976e962',
    messagingSenderId: '824061143111',
    projectId: 'task-manager-94870',
    storageBucket: 'task-manager-94870.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs4W4OX53uTXM6CW_1vIamRRQuU0PXiQM',
    appId: '1:824061143111:ios:2d0f218bf9f9732a76e962',
    messagingSenderId: '824061143111',
    projectId: 'task-manager-94870',
    storageBucket: 'task-manager-94870.appspot.com',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs4W4OX53uTXM6CW_1vIamRRQuU0PXiQM',
    appId: '1:824061143111:ios:7672468e74517b5e76e962',
    messagingSenderId: '824061143111',
    projectId: 'task-manager-94870',
    storageBucket: 'task-manager-94870.appspot.com',
    iosBundleId: 'com.example.taskManagerApp.RunnerTests',
  );
}
